name: Deploy Docker Image

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Pull Docker image
    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/githubaction:latest

    # Step 4: Deploy Docker image to Kubernetes
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        kubectl apply -f k8s/deployment.yaml
