name: Deploy Docker Image

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Pull Docker image
    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/githubaction:latest

    # Step 4: Configure kubeconfig
    - name: Configure kubeconfig
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        echo "$KUBECONFIG_BASE64" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl config view # Validate the kubeconfig file

    # Step 5: Validate Kubernetes Cluster
    - name: Validate Kubernetes Cluster
      run: |
        kubectl cluster-info # Ensure the cluster is accessible
        kubectl get nodes    # Verify node availability

    # Step 6: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f manifests/ --validate=false # Deploy manifests with optional validation disabled

    # Step 7: Validate Deployment
    - name: Validate Deployment
      run: |
        kubectl get pods -o wide   # List all pods with details
        kubectl get services -o wide # List all services with details
